#!/bin/bash

if [ -d ./mud/logs ]; then
	mv ./mud/logs/session.log ./mud/logs/session.log.old
else
	mkdir ./mud/logs
fi

if [ ! -d ./tmp ]; then
	mkdir tmp
fi

date > ./mud/logs/session.log

if [ -f ./dump ]; then
	./bin/driver ./mud.dgd ./dump 2>> ./mud/logs/session.log &
	echo DGD started from dump...
else 
	./bin/driver ./mud.dgd 2>> ./mud/logs/session.log &
	echo DGD started from scratch...
fi

